pages/urls.py
from django.urls import path
from .views import HomeView
from travel.views.contact_views import ContactFormView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('contact/', ContactFormView.as_view(), name='contact')
]

travel_agency/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('pages.urls')),
    path('', include('travel.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # path('', include('travel.urls.trip_urls')),
    # path('', include('travel.urls.booking_urls')),
    # path('', include('travel.urls')),

travel/models/booking_models.py
from django.db import models, transaction
from .trip_models import Trip
from .location_models import Airport


from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.conf import settings
from decimal import Decimal

# # # Booking Model # # #

##########################################################################
from travel.services.airport_services import calculate_plane_ticket_cost
###########################################################################

class Booking(models.Model):
    MEAL_PLAN_CHOICES = [
    ('None', 'No Meal Plan'),        # No meal plan selected
    ('BB', 'Bed and Breakfast'),     # BB: Bed and Breakfast
    ('HB', 'Half Board'),            # HB: Half Board
    ('FB', 'Full Board'),            # FB: Full Board
    ('AI', 'All Inclusive')]         # AI: All Inclusive

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE)
    booking_date = models.DateTimeField(default=timezone.now)
    meal_plan = models.CharField(max_length=4, choices=MEAL_PLAN_CHOICES,default='None',
                                 help_text='Select meal plan for booking')
    tickets_adult = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)],
                                                help_text='Tickets for adults')
    tickets_child = models.PositiveIntegerField(default=0, help_text=' Tickets for children')

    wants_flight = models.BooleanField(default=False, help_text='Include flight tickets?')
    from_airport = models.ForeignKey('travel.Airport', null=True, blank=True, on_delete=models.SET_NULL,
                                     help_text='Departure Airport')
    wants_airport_pickup = models.BooleanField(default=False, help_text='Pick up from airport?')
    wants_airport_dropoff = models.BooleanField(default=False, help_text='Drop off at airport?')

    airplane_price = models.IntegerField(default=0, help_text='Plane Tickets cost')
    airport_price = models.IntegerField(default=0, help_text='Total cost of airport services')

    wants_car_rental = models.BooleanField(default=False, help_text='Include car rental?')
    car_rental_days = models.IntegerField(default=0, help_text='Car rental days')

    car_rental_cost = models.IntegerField(default=0, help_text='Total cost of car rental services')

    booking_price = models.IntegerField(default=0)

    paid = models.BooleanField(default=False)

    booking_number = models.CharField(max_length=20, unique=True, blank=True, null=True)

    def generate_booking_number(self):
        city_code = self.trip.city.name[:3].upper()
        prefix = f"BKN{city_code}"

        # Get all booking numbers for this city
        existing_numbers = (
            Booking.objects
            .filter(booking_number__startswith=prefix)
            .values_list('booking_number', flat=True)
        )

        # Extract and convert suffixes to integers
        suffixes = []
        for bn in existing_numbers:
            suffix = bn[len(prefix):]
            if suffix.isdigit():
                suffixes.append(int(suffix))

        next_number = max(suffixes, default=0) + 1
        return f"{prefix}{next_number}"

    def total_tickets(self):
        return self.tickets_adult + self.tickets_child

    def calculate_meal_plan_cost(self):
        total_tickets = self.tickets_adult + self.tickets_child
        duration = self.trip.calculate_duration()

        if self.meal_plan == None:
            return 0
        
        if self.meal_plan == 'BB':
            return (self.trip.hotel.bb_price * total_tickets) * duration
        
        if self.meal_plan == 'HB':
            return (self.trip.hotel.hb_price * total_tickets) * duration
        
        if self.meal_plan == 'FB':
            return (self.trip.hotel.fb_price * total_tickets) * duration

        if self.meal_plan == 'AI':
            return (self.trip.hotel.ai_price * total_tickets) * duration

        return 0 # with no meal plan selected return 0

########################################################################


    def calculate_airport_cost(self):
        cost = 0
        to_airport = self.trip.airport # destination of trip
        from_airport = self.from_airport # selected by user

        if self.wants_flight and from_airport:

            from_country = from_airport.city.country
            from_continent = from_country.continent

            to_country = to_airport.city.country
            to_continent = to_country.continent

            plane_ticket_cost = calculate_plane_ticket_cost(
                to_airport.standard_plane_ticket,
                from_country, from_continent,
                to_country, to_continent
            )

            cost += plane_ticket_cost * self.total_tickets()
            

            if self.wants_airport_pickup:
                cost += to_airport.airport_pick_up_cost * self.total_tickets()

            if self.wants_airport_dropoff:
                cost += to_airport.airport_drop_off_cost * self.total_tickets()

        return cost

########################################################################

    def calculate_car_rental_cost(self):
        cost = 0
        if self.wants_car_rental and self.car_rental_days != 0:
            cost_per_day = self.trip.city.car_rental_cost
            cost = cost_per_day * self.car_rental_days
            self.car_rental_cost = cost
            return cost
        return 0


########################################################################

    def total_cost(self):
        adult_ticket_price = Decimal(self.trip.calculate_adult_price(self.tickets_adult))
        child_ticket_price = Decimal(self.trip.calculate_child_price(self.tickets_child))
        # Meal plan cost
        meal_plan_cost = Decimal(self.calculate_meal_plan_cost())

        airport_cost = Decimal(self.calculate_airport_cost())  ###########
        self.airport_price = int(airport_cost)

        car_rental_cost = Decimal(self.calculate_car_rental_cost())

        self.booking_price = meal_plan_cost + adult_ticket_price + child_ticket_price + airport_cost + car_rental_cost

        return float(self.booking_price)

    def clean_tickets(self):
        booking_tickets = self.total_tickets()
        if booking_tickets > self.trip.tickets:
            raise ValidationError(f'Only {self.trip.tickets} tickets left on this trip')

    def clean_airport(self):
        if self.wants_flight and not self.from_airport:
            raise ValidationError('Flight requested, please select airport')

    def clean_car(self):
        if self.wants_car_rental and self.car_rental_days <= 0:
            raise ValidationError('Please enter valid car rental days')
        

    def clean(self):
        self.clean_tickets()
        self.clean_airport()
        self.clean_car()

    def add_tickets(self):
        booked_tickets = self.total_tickets()
        self.trip.tickets -= booked_tickets
        self.trip.save()

    def delete_tickets(self):
        booked_tickets = self.total_tickets()
        self.trip.tickets += booked_tickets
        self.trip.save()
        
    def save(self, *args, **kwargs):
        self.total_cost()

        if not self.pk:
            if not self.booking_number:
                self.booking_number = self.generate_booking_number()

            self.add_tickets()
        else:
            old = Booking.objects.get(pk=self.pk)
            old_tickets = old.total_tickets()
            new_tickets = self.total_tickets()
            difference = new_tickets - old_tickets

            self.trip.tickets -= difference
            self.trip.save()
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        if self.pk:
            self.delete_tickets()
        super().delete(*args, **kwargs)

    def __str__(self):
        tickets = self.total_tickets()
        trip = self.trip
        return f'{tickets} tickets for {trip}'
    



    ##### TO BE CONTINUED ###################

#   BOOKING CANNOT BE CREATED BY SAME USER IF ANOTHER BOOKING HAS SAME DATES
#   BUT CAN CREATE BOOKINGS IF DATES ARE DIFFERENT

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2')

    def clean_username(self):
        username = self.cleaned_data['username']
        if CustomUser.objects.filter(username__iexact=username).exists():
            raise ValidationError('This username is already taken')
        return username
    


from django.forms import ModelForm
from .models import CustomUser
from django import forms
from travel.models import Country, City
class CustomUserForm(ModelForm):
    class Meta:
        model = CustomUser
        fields = ['name', 'surname', 'country', 'city']

    name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={
            'autofocus': 'autofocus',
            'autocomplete': 'name'
        })
    )

    surname = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={
            'autocomplete': 'surname'
        })
    )

    country = forms.ModelChoiceField(
        queryset=Country.objects.all(),
        empty_label="Select a country",
        required=False
    )

    city = forms.ModelChoiceField(
        queryset=City.objects.all(),
        empty_label="Select a city",
        required=False
    )

    # When initializing the form, populate the fields with data from user
    def __init__(self, *args, **kwargs):
        user = kwargs.get('instance')
        super().__init__(*args, **kwargs)

        # Set default city queryset to empty
        self.fields['city'].queryset = City.objects.none()

        # Handle POST request (country selection)
        self.fields['city'].queryset = City.objects.none()

        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                self.fields['city'].queryset = City.objects.filter(country_id=country_id)
            except (ValueError, TypeError):
                pass
        elif user and user.country:
            self.fields['city'].queryset = City.objects.filter(country=user.country)

        # Populate other fields
        if user:
            self.fields['name'].initial = user.name
            self.fields['surname'].initial = user.surname
            self.fields['country'].initial = user.country
            self.fields['city'].initial = user.city

accounts/views/activation_views.py
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator
from django.shortcuts import render
from django.views import View
from accounts.models import CustomUser
from django.contrib import messages
from django.shortcuts import redirect

class ActivateAccountView(View):
    def get(self, request, uid, token):
        try:
            # Decode the UID and get the user
            uid = urlsafe_base64_decode(uid).decode()
            user = CustomUser.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, CustomUser.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            messages.success(request, "Your account has been activated. You can now log in.")
            return redirect('login')
        else:
            messages.error(request, "Activation link is invalid or has expired.")
            return redirect('register')

accounts/views/login_views.py
from django.contrib.auth.views import LoginView
from accounts.forms import CustomUserCreationForm

class CustomLoginView(LoginView):
    template_name = 'accounts/auth/login_register.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_type'] = 'login'
        # Add the registration form instance to the context
        context['login_form'] = CustomUserCreationForm()  # Include registration form in the context
        return context

accounts/views/profile_views.py
from accounts.models import CustomUser
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView
from django.urls import reverse_lazy
from django.shortcuts import redirect
from accounts.services import get_user_booking_context
from django.views.generic import UpdateView
from accounts.forms import CustomUserForm

class UserProfileView(LoginRequiredMixin, DetailView):
    model = CustomUser
    template_name = 'accounts/profile/profile.html'
    context_object_name = 'profile_user'
    slug_field = 'username'
    slug_url_kwarg = 'username'

    def dispatch(self, request, *args, **kwargs):
        # Get the user object based on the username in the URL
        user = self.get_object()
        
        # If the logged-in user is not the profile owner, redirect them
        if user != request.user:
            return redirect('home')  # Or redirect to any other page
        
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.object

        # Call the service function to get the booking data
        booking_context_data = get_user_booking_context(user)

        # Update the context with the data from the service function
        context.update(booking_context_data)

        return context

class EditProfileView(LoginRequiredMixin, UpdateView):
    model = CustomUser
    form_class = CustomUserForm
    template_name = 'accounts/profile/edit_profile.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'

    def dispatch(self, request, *args, **kwargs):
        user = self.get_object()
        if user != request.user:
            return redirect('home')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('user_profile', kwargs={'username': self.object.username})

accounts/views/register_views.py
from django.contrib.auth.forms import AuthenticationForm
from accounts.forms import CustomUserCreationForm
from django.views.generic.edit import CreateView
from accounts.models import CustomUser
from django.contrib.auth.tokens import default_token_generator
from django.conf import settings
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.shortcuts import render
from django.core.mail import send_mail


class RegisterView(CreateView):
    model = CustomUser
    form_class = CustomUserCreationForm
    template_name = 'accounts/auth/login_register.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_type'] = 'register'
        context['register_form'] = CustomUserCreationForm()
        context['login_form'] = AuthenticationForm()
        return context
    
    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False  # Don't log them in yet
        user.save()

        # Prepare email verification
        current_site = get_current_site(self.request)
        subject = 'Activate Your Account'
        message = render_to_string('accounts/activation/activation_email.html', {
            'user': user,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            'token': default_token_generator.make_token(user),
        })

        send_mail(
            subject,
            message,
            settings.DEFAULT_FROM_EMAIL,
            [user.email],
            fail_silently=False,
        )

        return render(self.request, 'accounts/activation/check_your_email.html')

accounts/templates/accounts/profile/profile.html
{% extends "base.html" %}

{% block title %}{{ profile_user.username }}'s Page{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'accounts/style.css' %}">
<div class="profile-page">

    <div class="container-presets centered-container account-info-container">
        <h2 class="title1-presets">{{ profile_user.username.title }}'s Page</h2>


        
        

        <div class="account-info-inner-container">
            <!-- <PROFILE INFO> -->
            <div class="account-info-profile-container">
                <div class="profile-picture-container">
                    <div class="profile-picture"></div>

                    <a href="{% url 'edit_profile' profile_user.username %}">
                        <button class="button-presets">Edit Profile</button>
                    </a>
                </div>
                <hr class="divider-presets">
                    
                <div class="profile-item-container">

                    <p class="profile-item"><strong>Username</strong> {{ profile_user.username.title }}</p>
                    <p class="profile-item"><strong>Email</strong> {{ profile_user.email }}</p>
                    <p class="profile-item"><strong>Name</strong> {{ profile_user.name.title }}</p>
                    <p class="profile-item"><strong>Surname</strong> {{ profile_user.surname.title }}</p>

                    <p class="profile-item"><strong>Country</strong> {{ profile_user.country }}</p>
                    <p class="profile-item"><strong>City</strong> {{ profile_user.city }}</p>
                    {% if profile_user.country %}
                    {% endif %}
                    
                </div>


                
            </div><!-- </PROFILE INFO> -->


            {% if paid_bookings %}
            <!-- <HISTORY CONTAINER> -->
            <div class="account-info-booking-history-container">

                <!-- <h1 class="booking-history-title">Booking <br> History</h1>    -->
    
                <!-- <BOOKING COLUMN> -->
                <div class="booking-column">
                    <h1 class="inner-container-presets booking-history-title">Booking</h1>
                    {% for booking in paid_bookings %}
                      
                        <!-- <BOOKING CARD> -->
                        <div class="inner-container-presets booking-card">
                            <h3 style="justify-self: center; align-self: center;">
                                {% if booking.booking_number is None %}
                                    <p>Booking</p>
                                {% else %}
                                    {{ booking.booking_number }}
                                {% endif %}
                            </h3>
                            <hr class="divider-presets">
                            <p>Trip: {{ booking.trip }}</p>
                            <p>Departure: {{ booking.trip.departure_date }}</p>
                            <p>Return: {{ booking.trip.return_date }}</p>
                            <hr class="divider-presets">
                            
                            <p>Adults: {{ booking.tickets_adult }} </p>
                            {% if booking.tickets_child %}
                            <p>Children: {{ booking.tickets_child }} </p>
                            {% endif %}
                            
                            <hr class="divider-presets">
                            
                            {% if booking.get_meal_plan_display != "No Meal Plan" %}
                            <p>Meal: {{ booking.get_meal_plan_display }}</p>
                            <hr class="divider-presets">
                            {% endif %}
                            
                            {% if booking.wants_flight %}
                            <p>Flight: Yes</p>
                            {% if booking.wants_airport_pickup %}
                            <p>Pick from airport: Yes</p>
                            {% endif %}
                            {% if booking.wants_airport_dropoff %}
                                <p>Drop to airport: Yes</p>
                                {% endif %}
                            <hr class="divider-presets">
                            {% endif %}
                            {% if booking.wants_car_rental %}
                            <p>Car Rental: {{ booking.car_rental_days }} day{{ booking.car_rental_days|pluralize }}</p>
                            <hr class="divider-presets">
                            {% endif %}
                            
                            <p>{{ booking.total_tickets }} Ticket{{ booking.total_tickets|pluralize }}</p>
                            
                        </div><!-- </BOOKING CARD> -->

                    {% endfor %}        
                   
                </div><!-- </BOOKING COLUMN> -->


                <!-- <INVOICE COLUMN> -->
                <div class="invoice-column">
                    <h1 class="inner-container-presets booking-history-title">Invoice</h1>
                    {% for booking in paid_bookings %}

                
                        <!-- <INVOICE CARD> -->
                        <div class="inner-container-presets invoice-card">
                            <h3 style="justify-self: center; align-self: center;">{{booking.invoice.invoice_number}}</h3>
                            <p>{{ booking.invoice.payment_date }}</p>
                            <hr class="divider-presets">
                            <p>Trip: {{ booking.trip }}</p>
                            <p>Departure: {{ booking.trip.departure_date }}</p>
                            <p>Return: {{ booking.trip.return_date }}</p>
                            <hr class="divider-presets">
                            <p>For {{ booking.tickets_adult }} adult{{ booking.tickets_adult|pluralize }}: ${{ booking.adult_price|floatformat:0 }}</p>
                            {% if booking.tickets_child %}
                                <p>For {{ booking.tickets_child }} child{{ booking.tickets_child|pluralize:"ren" }}: ${{ booking.child_price|floatformat:0 }}</p>
                            {% endif %}

                            {% if booking.total_tickets > 1 %}
                                <p>For {{ booking.total_tickets }} Tickets: ${{ booking.total_price|floatformat:0 }}</p>
                            {% endif %}
                            <hr class="divider-presets">
                            
                            {% if booking.get_meal_plan_display != "No Meal Plan" %}
                                <p>Meal for {{ booking.total_tickets }}: ${{ booking.calculate_meal_plan_cost|floatformat:0 }}</p>
                                <hr class="divider-presets">
                            {% endif %}

                            {% if booking.wants_flight %}
                                <p>Plane Tickets ${{ booking.plane_tickets_cost }}</p>

                                {% if booking.wants_airport_pickup %}
                                    <p>Airport Pick Up: ${{ booking.airport_pickup_total }}</p>
                                {% endif %}
                                {% if booking.wants_airport_dropoff %}
                                    <p>Airport Drop Off: ${{ booking.airport_dropoff_total }}</p>
                                {% endif %}
                                <p>Total Airport: ${{ booking.calculate_airport_cost|floatformat:0 }}</p>
                                <hr class="divider-presets">
                            {% endif %}

                            {% if booking.wants_car_rental  %}
                                <p>Car Rental: ${{ booking.car_rental_cost }}</p>
                                <hr class="divider-presets">
                            {% endif %}
                            
                            <p>Total Sum: ${{ booking.booking_price }}</p>
                        </div><!-- </INVOICE CARD> -->
                

                    {% endfor %}
        
                </div><!-- </INVOICE COLUMN> -->        

                        
                    
                
            </div><!-- </HISTORY CONTAINER> -->
            {% endif %}

        </div>

    </div>

    <!-- <PENDING BOOKINGS CONTAINER> -->
    <div id="pending-bookings" class="container-presets centered-container">



        <h1 class="title1-presets">Pending Bookings</h1>

        {% if bookings %}
            <div class="account-info-booking-container ">
                {% for booking in bookings %}


                



                    <div class="account-info-booking inner-container-presets" style="margin-bottom: 30px;">
                        <h2 class="account-info-booking-title title2-presets">{{ booking.booking_number }}</h2>
                        <hr class="divider-presets">
                        

                        <h3 class="account-info-booking-title2">Dates</h3>
                        <p class="account-info-booking-item">Booking Date: {{ booking.booking_date }}</p>
                        <p class="account-info-booking-item">Departure: {{ booking.trip.departure_date }}</p>
                        <p class="account-info-booking-item">Return: {{ booking.trip.return_date }}</p>
                        <hr class="divider-presets">

                        <h3 class="account-info-booking-title2">Tickets</h3>
                        <p class="account-info-booking-item">Adults: {{ booking.tickets_adult }}</p>
                        {% if booking.tickets_child != 0 %}
                        <p class="account-info-booking-item">Children: {{ booking.tickets_child }}</p>
                        {% endif %}
                        <div class="account-info-price-item">Price for Tickets ${{ booking.price_for_tickets|floatformat:0 }}</div>
                        <hr class="divider-presets">

                        {% if booking.get_meal_plan_display != 'No Meal Plan' %}
                        <h3 class="account-info-booking-title2">Meal</h3>
                        <p class="account-info-booking-item">{{ booking.get_meal_plan_display }}</p>
                        <div class="account-info-price-item">Meal Cost ${{ booking.calculate_meal_plan_cost|floatformat:0 }}</div>
                        {% else %}
                        <h3 class="account-info-booking-title2">Meal ❌ </h3>
                        {% endif %}
                        <hr class="divider-presets">

                        <h3 class="account-info-booking-title2">Airport{% if booking.wants_flight %} ({{ booking.from_airport.code }}) ➜ ({{ booking.trip.airport.code }})
                            {% else %} ❌ {% endif %}</h3>
                        {% if booking.wants_flight  %}
                        <div class="account-info-booking-item">From<br> {{ booking.from_airport }} </div>
                        <div class="account-info-booking-item">To<br> {{ booking.trip.airport }} </div>
                            {% if booking.wants_airport_pickup %}
                                <div class="account-info-booking-item">Pick Up ✅ </div>
                            {% endif %}
                            {% if booking.wants_airport_dropoff %}
                                <div class="account-info-booking-item">Drop Off ✅ </div>
                            {% endif %}
                        <div class="account-info-price-item">Airport Price: {{ booking.airport_price }}</div>
                        {% else %}
                        {% endif %}
                        <hr class="divider-presets">

                        {% if booking.wants_car_rental  %}
                            <h3 class="account-info-booking-title2">Car Rental </h3>
                            <div class="account-info-booking-item">Days: {{ booking.car_rental_days }}</div>
                            <div class="account-info-price-item">Rental Cost: {{ booking.car_rental_cost }}</div>
                        {% else %}
                            <h3 class="account-info-booking-title2">Car Rental ❌ </h3>
                        {% endif %}
                        <hr class="divider-presets">

                        <div class="account-info-booking-item account-info-booking-total-price">Booking Price<br>${{ booking.booking_price }}</div>
                        <form action="{% url 'booking_pay' pk=booking.pk %}" method="post" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" class="button-presets account-info-booking-pay-button">Pay Booking</button>
                        </form>
                        
                        <hr class="divider-presets">

                        <a href="{% url 'booking_update' pk=booking.pk %}"><button class="button-presets account-info-booking-edit-button">Edit Booking</button></a>
                        <a href="{% url 'booking_delete' pk=booking.pk %}"><button class="button-presets account-info-booking-delete-button">Delete Booking</button></a>

                    </div>

                {% endfor %}
            </div>
        {% else %}
            <h1 class="title2-presets">No unpaid bookings.</h1>
        {% endif %}
    </div>
</div>
</div>

{% endblock %}